### ISSUE TITLE
CoinDesk returns comma in price when over 1000USD

### ISSUE THREAD

**Issue by BangorSkis** [dursk/bitcoin-price-api#8]
Just noticed this error when calling CoinDesk().get_current_price() as the price is now over 1,000 USD:

```decimal.InvalidOperation: Invalid literal for Decimal: u'1,004.8813'```

Wrapping coindesk.py line 14 in a str().replace() as such seems to resolve.

```python
        price = data['bpi'][currency]['rate']
```
becomes
```python
        price = str(data['bpi'][currency]['rate']).replace(',', '')
```

Might have to do on the rest of the price functions as well?

New to Python and GitHub in general so didn't actually fork and try to submit a PR.

**Comment by PokestarFan** [comment]
#10 This should take care of it
